#!/usr/bin/env bash
# Generated by ralph-cli
# Run a single automation iteration

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RALPH_DIR="$SCRIPT_DIR/.ralph"

if [ ! -f "$RALPH_DIR/prompt.md" ]; then
  echo "Error: .ralph/prompt.md not found. Run 'ralph init' first."
  exit 1
fi

PROMPT=$(cat "$RALPH_DIR/prompt.md")

# Detect if running in a container
is_container() {
  # Check DEVCONTAINER env var (set by ralph docker setup)
  [ "$DEVCONTAINER" = "true" ] && return 0
  # Check for /.dockerenv file (Docker creates this)
  [ -f "/.dockerenv" ] && return 0
  # Check /proc/1/cgroup for container hints
  if [ -f "/proc/1/cgroup" ]; then
    grep -qE "(docker|podman|lxc|containerd)" /proc/1/cgroup 2>/dev/null && return 0
  fi
  # Check container environment variable
  [ "$container" = "podman" ] || [ "$container" = "docker" ] && return 0
  return 1
}

CLAUDE_ARGS="--permission-mode acceptEdits"
if is_container; then
  echo "Detected container environment - running with --dangerously-skip-permissions"
  echo ""
  CLAUDE_ARGS="$CLAUDE_ARGS --dangerously-skip-permissions"
fi

claude $CLAUDE_ARGS \
  -p "@$RALPH_DIR/prd.json @$RALPH_DIR/progress.txt $PROMPT"
